### ISSUE TITLE
Don't use variables before they're defined

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-appcues#1]
As noted [here](https://github.com/segment-integrations/analytics.js-integration-appcues/blob/bce2a02f852cb0abfa29b58d0bced32751a95a97/.eslintrc#L7), this linting error should be fixed.

**Comment by hijonathan** [comment]
@ndhoule is this something I can help with?

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
